# Setup
title:        ORFEO Soundworks Careers
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Kyle Kim
  url:        https://www.orfeosound.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown