# Setup
title:        ORFEO Soundworks Careers
tagline:      
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Kyle Kim
  url:        mailto:kyle@orfeosound.com
  
# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown